//! Damsels Game Models
//!
//! This module contains all database table definitions for the game.
//!
//! Table access traits (generated by SpacetimeDB) are internal implementation
//! details and not part of the public API.

// Modules are pub(crate) — accessible within the crate for trait imports,
// but not exposed externally
pub(crate) mod enums;
pub(crate) mod user;
pub(crate) mod player;
pub(crate) mod activity;
pub(crate) mod equipment;
pub(crate) mod player_activity;
pub(crate) mod player_history;
pub(crate) mod room;
pub(crate) mod room_activity;

// Explicit public exports — only types, not traits
pub use enums::{ActivityKind, ActivityStatus, InvitationStatus, PlayerRole, RoomActivityStatus, RoomInvitationStatus, UserRole};
pub use user::User;
pub use player::{Player, PlayerCategoryPreference};
pub use activity::{Activity, ActivityCategory, ActivityPrerequisite};
pub use equipment::{ActivityEquipment, Equipment};
pub use player_activity::{PlayerActivity, PlayerUnlockedActivity, PrerequisiteVouch};
pub use player_history::PlayerHistory;
pub use room::{Invitation, Room, RoomInvitation, RoomMember};
pub use room_activity::{ActivityParticipant, RoomActivity};

